export function getBackendStandardsBlock(): string[] {
  return [
    "### Backend Standards",
    "",
    "Controllers:",
    "- request parsing",
    "- response handling",
    "",
    "Services:",
    "- business logic",
    "",
    "Middleware:",
    "- cross-cutting concerns",
    "",
    "Validators:",
    "- request validation",
    "",
    "Routes:",
    "- endpoint definitions only",
    "",
    "### API Design",
    "",
    "Use REST conventions.",
    "Use plural resources.",
    "Use consistent naming.",
    "",
    "### API Responses",
    "",
    "Success shape:",
    '`{ "success": true, "data": ... }`',
    "",
    "Failure shape:",
    '`{ "success": false, "message": ... }`',
    "",
    "### Error Handling",
    "",
    "Never swallow errors.",
    "Return meaningful messages and correct status codes.",
    "",
    "### Validation",
    "",
    "Validate all external input.",
    "Never trust request body, params, or query values.",
  ];
}

export function getBackendAuthenticationBlock(): string[] {
  return [
    "### Authentication",
    "",
    "Use JWT for protected flows when token auth is selected.",
    "Store passwords using bcrypt or argon2 based on the current scaffold.",
    "Never store plain text passwords.",
    "Never expose password hashes.",
  ];
}
