export function getFrontendStandardsBlock(): string[] {
  return [
    "### Frontend",
    "",
    "Keep components focused.",
    "Prefer composition and reusable components.",
    "Avoid large monolithic components and duplicated logic.",
    "",
    "### State",
    "",
    "Prefer local UI state first.",
    "Use global state only when necessary.",
    "Use TanStack Query for server-state flows when included in the scaffold.",
    "",
    "### API Access",
    "",
    "Do not place API calls directly inside presentational UI components.",
    "Place API logic in dedicated modules and consume it through hooks or query layers.",
    "",
    "### UI Style",
    "",
    "Avoid gradients, glassmorphism, neon colors, excessive shadows, and decorative animation.",
    "Prefer clean spacing, practical forms, readable tables, and clear navigation.",
    "",
    "### Accessibility",
    "",
    "Always label inputs, provide button text, and use semantic HTML.",
  ];
}
